AllCops:
  Exclude:
  - 'bin/**/*'
  - 'config/**/*'
  - 'db/migrate/*'
  - 'db/schema.rb'
  - 'vendor/**/*'
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact
