AllCops:
  Exclude:
  - 'bin/**/*'
  - 'config/**/*'
  - 'db/migrate/*'
  - 'db/schema.rb'
  - 'vendor/**/*'

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/RaiseArgs:
  EnforcedStyle: compact
